# Generated by Django 5.1 on 2024-08-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='unique_hash',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
